### ISSUE TITLE
Try-catch around this code to output a more helpful error

### ISSUE THREAD

**Issue by bean5** [mvndaai/testlink-connect#3]
It appears that in the case that a test case name is not unique, the following occurs:

filename.js:30
            params.testcaseid = tcid.struct.id;
                                           ^
TypeError: Cannot read property 'id' of undefined
    at node_modules/testlink-connect/lib/advanced_methods.js:30:44
    at node_modules/testlink-connect/lib/utilities.js:174:3
    at IncomingMessage.<anonymous> (node_modules/testlink-connect/lib/utilities.js:45:17)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
make: **\* [testServices] Error 1

**Comment by mvndaai** [comment]
I am afraid that If I get into the code at the moment I will break something, so I would accept a pull request. Reopen this if you create one.
